### ISSUE TITLE
what does macc stand for ?

### ISSUE THREAD

**Issue by Coderx7** [dgschwend/netscope#10]
Hello, Thank you for your script. 
Can you elaborate what macc stands for ?

**Comment by dgschwend** [comment]
MACC = Multiply-Accumulate Operation = 1 multiplication + 1 addition
These are the basic math operations needed for computing the convolution.

**Comment by sagar-kale-ai** [comment]
Correct me if i am wrong: 
matrix A = (m,n)  # m:rows, n: cols
matrix B = (n,p)  # n:rows, p:cols

number of flops for AxB = m*p [n + (n-1)]  # n: number of multiplications and (n-1): number of additions

e.g Input Image = (3,300,300) in matrix form it will be A =(27,90000)
Conv Filter = (64,3,3,3) in matrix form it will be B = (64,27)

Number of flops = 64*90000 (27 + (27 -1)) = **305280000 ~ 305 MFlops** is not matching MACC.

Can you explain please ? How MACC is calculated?


![test3](https://user-images.githubusercontent.com/12183255/29122890-81b74e68-7d31-11e7-92ad-bf1de046bda2.JPG)
![test1](https://user-images.githubusercontent.com/12183255/29122891-81ba7a20-7d31-11e7-98e5-a481ba88e958.JPG)
![test2](https://user-images.githubusercontent.com/12183255/29122892-81c50ea4-7d31-11e7-88fc-4357a33a13da.JPG)

**Comment by dgschwend** [comment]
Hi Sagartesla

As Explained above:
Netscope analyzer counts 1 MACC = 1 multiply + 1 add (= 2 (FL)OPs). You are counting the operations separately, thus the ~2x factor between 155M MACCs and 305M FLOPs.

For the actual code, see https://github.com/dgschwend/netscope/blob/406deb0ea3e9b8015f28e4b4a70532df729d94e9/src/analyzer.coffee#L77

Netscope analyzer assumes direct convolution, which is the most computationally efficient way to compute a convolutional layer (in other words, the computed maccs is the minimum number of ops required to compute the layer).
However, I think the matrix-matrix multiplication approach should require approximately the same number of operations (just lots and lots more memory!).
