### ISSUE TITLE
Concat error since last update

### ISSUE THREAD

**Issue by rejay015** [dgschwend/netscope#12]
Hi dgschwend,

Glad to contact you again.
I've found a concat parameter error of this netscope project, since the project was updated 7days ago.
You can find it at "fire2/concat", the output channel should be 128 but was demonstrated as 192.

See the link or picture below.
http://dgschwend.github.io/netscope/#/preset/zynqnet

![concat_error_at_fire2_concat](https://cloud.githubusercontent.com/assets/16098402/25839519/9aa4fdb2-34ca-11e7-8590-97e0c94780fe.png)

**Comment by dgschwend** [comment]
Hi rejay015
Sorry for the delay, I'm currently on vacation. I introduced a bug in analyzer.coffee in the last commit. Before the line
`   d.chIn += p.analysis.chOut for p in n.parents`
you need to add one line saying
`   d.chIn =0`
That should fix it. I'm currently on my phone, so cannot recompile, but will fix this next week.
Thanks for spotting + reporting!
David

**Comment by rejay015** [comment]
Have a nice vacation, I guess it's a long journey, out of Europe   ^_^

**Comment by dgschwend** [comment]
fixed in 234e8f7d1d37ba1f8dc9b487c7e78cdb6931acc1
