### ISSUE TITLE
the total activation memory is not correct

### ISSUE THREAD

**Issue by PattyLiang** [dgschwend/netscope#14]
Hi dgschwend,

I've found a error of this netscope project.
For example, the sum of activation memory in Googlenet is nearly 102.1M (input 227x227, batch 10),
but the total activation memory show that is nearly 103.73M.

The sum of activation memory in ZynqNet is nearly 8.51M (input 256x256, batch 1),
but the total activation memory show that is nearly 8.8M.

**Comment by dgschwend** [comment]
Fixed, see https://github.com/dgschwend/netscope/issues/15.
