### ISSUE TITLE
How to calculate the total activation? 

### ISSUE THREAD

**Issue by tankienleong** [dgschwend/netscope#15]
Hi, may I know how you calculate the total activation?
I run a simple prototxt in the netscope to check the activation value of each layer. There are only two layers in my prototxt, i.e., data layer and conv1. The netscope shows the activation value for data layer is 4 and the activation value for conv1 is 1, but the total activation is 9.
![screenshot from 2017-05-30 10 30 51](https://cloud.githubusercontent.com/assets/25731934/26566485/27a3852e-4526-11e7-8fa3-f9a4cdb66268.png)

**Comment by dgschwend** [comment]
Hi @tankienleong 
Thanks for testing and reporting. I was able to reproduce and locate the problem.
The activation memory of the initial layer was counted twice, thus the error. Fixed in commit 406deb0ea3e9b8015f28e4b4a70532df729d94e9.
Best regards
David
