### ISSUE TITLE
Unknown Layer: power

### ISSUE THREAD

**Issue by twmht** [dgschwend/netscope#16]
@dgschwend 

Does this recognize power layer (http://caffe.berkeleyvision.org/tutorial/layers/power.html) ? 

thank you

**Comment by sovrasov** [comment]
@twmht take a look at #20

**Comment by dgschwend** [comment]
Thanks for the report. Power layers are now supported since commit https://github.com/dgschwend/netscope/commit/4deae73f9fdd77b075a45e1d9158c22f154e9cd7 (dimension propagation as well as complexity analysis).
