### ISSUE TITLE
Wrong parameter count

### ISSUE THREAD

**Issue by marph91** [dgschwend/netscope#17]
Hello,
shouldn't there be the bias count added to the parameter count?

For example in the details of ZynqNets `conv1` layer there is written `1728` (`= 3*3*3*64`) parameter. Shouldn't it be `1792` (`= 3*3*3*64 + 64`)?

**Comment by dgschwend** [comment]
Indeed! Bias parameters were not counted. Fixed in commit https://github.com/dgschwend/netscope/commit/009a9f81e691ef6018d30a4a4334af898f862cc1.
