### ISSUE TITLE
How to calcucate the value of activation ?

### ISSUE THREAD

**Issue by FreeApe** [dgschwend/netscope#18]
Hi, Is the size of the CAFFE model the size of PARAM?  what is the size of activation?  (caffemodel size == PARAM size + activation size). I'am confused. thx.

**Comment by dgschwend** [comment]
.caffemodel size = size of PARAM
Activation size is the minimum amount of memory (RAM / GPU DDR / internal SRAM) needed for the computed results (=activations) of each layer.

**Comment by FreeApe** [comment]
@dgschwend hi,dgschwend,  In fact , I trained a caffemodel(21.5M) which the size is approximately equal to the sum of PARAM_SIZE(5.77M) and ACTIVATION_SIZE(18.95).   The prototxt file is [https://github.com/chuanqi305/MobileNet-SSD/blob/master/MobileNetSSD_deploy.prototxt](https://github.com/chuanqi305/MobileNet-SSD/blob/master/MobileNetSSD_deploy.prototxt) 

, your netscope's result : 

variable| size
-- | --
activation | 18.95M
param |5.77M

so, I'am confused.

**Comment by dgschwend** [comment]
Netscope Analyzer reports the number of parameters (param count), not Megabytes. This allows estimation of the model size also in float16, int8, ... formats.
5.77 Million parameters in float32 = 5.77M*4B = 23MB. Some space can be saved thanks to the binary prototxt format of the caffemodel file, thus 21.5MB.

**Comment by FreeApe** [comment]
😓😓😓Got it. Thanks for your reply.  @dgschwend
