### ISSUE TITLE
How to export calculation counts for each layer?

### ISSUE THREAD

**Issue by hosea1008** [dgschwend/netscope#19]
Hello, could you please tell me how do you export the calculation counts of each layer? especially those relu and pooling layers which is not so easy to export from convolution operations...Thanks a lot~

**Comment by dgschwend** [comment]
Sorry, I don't understand your question. Do you want to export the displayed numbers to some spreadsheet tool?
You can generate Excel-compatible output data by clicking on "Excel-compatible Analysis Results (experimental)" at the very bottom of the page. However, this currently only includes Conv layers. If you need this data also for the other layer types, you can easily change the following line to also include Relu/Pool/... layers: https://github.com/dgschwend/netscope/blob/780fa208c75dddb6007dc7e3afe1503a5b3df27d/src/renderer.coffee#L196
You would need to fork the project and change / recompile / launch locally for this to work.
You might also be able to hack the JavaScript (around line 19057 in netscope.js) in your browser before clicking the link...
