### ISSUE TITLE
Visualize network from repo

### ISSUE THREAD

**Issue by mrgloom** [dgschwend/netscope#2]
Can I visualize network from repository, not from gist?
For example:
https://github.com/mrgloom/kaggle-dogs-vs-cats-solution/blob/master/learning_from_scratch/Models/AlexNet/deploy.prototxt

**Comment by dgschwend** [comment]
That's currently not implemented. I'd recommend you copy the contents of this "deploy.txt" to your clipboard, and paste it into the Netscope Editor manually. Shift-Enter to update the visualization.

––
David Gschwend • +41 79 552 74 00 • Winkelriedstr. 56 • 6003 Luzern
