### ISSUE TITLE
Error when the network name is undefined

### ISSUE THREAD

**Issue by sovrasov** [dgschwend/netscope#21]
When the `name` field is not specified in .prototxt, the tool shows `Untitled Network` title and can't handle the input dimensions. It doesn't show any error message, so it's hard to understand why the blob dimensions are NaNs.
![image](https://user-images.githubusercontent.com/5373517/33600405-33cabb5a-d9ba-11e7-8bc4-4ef3c434f8b9.png)
After the name was specified, the dimensions became normal:
![image](https://user-images.githubusercontent.com/5373517/33600462-58dcb916-d9ba-11e7-93b0-90586b98ef02.png)

@dgschwend can you fix this behavior? There are two variants: show a error message or ignore missing `name` and draw the network as usual.

**Comment by dgschwend** [comment]
Thanks for the report, that's confusing indeed! I've just added some additional error-handling for unspecified network names in d71f25a.
