### ISSUE TITLE
How to modify this project to adapt for self-written layers?

### ISSUE THREAD

**Issue by luofanghao** [dgschwend/netscope#4]
Hi, thanks for this work~ it is really useful.
I modified this project ( mainly in analyzer.coffee) to make it adapt for some of my own layers and parameters. 
But I did not find how to re-compile this project to make it work (I konw I should use  [coffee](http://coffeescript.org/) but not sure how to compile the whole project ). Could you give me a hint about this?
Thanks again!

**Comment by dgschwend** [comment]
Hi @luofanghao! I'm currently on the go an cannot check all the requirements. But from my memory:
- There's a bash script at `scripts/watch.sh`, which constantly monitors your .coffee-files and recompiles them to JavaScript on every save. You should run the script from the root directory of the project.
- The script has quite a few requirements. It's based on node.js, and you also need the following node.js packages (simply call `npm <package-name>` once you have node.js installed):
  - coffeeify
  - browserify
  - watchify

Give it a try, and if you have problems, comment again and I will check once I'm back at the office.
I'm glad the project is useful to you! :wink:
