### ISSUE TITLE
What does "macc" mean in the analysis of computation? Thanks 

### ISSUE THREAD

**Issue by LiYijin** [dgschwend/netscope#7]
I don't know "macc" means what?
I know 'add' means addition, exp means exponential,
Really Thanks!

**Comment by LiYijin** [comment]
Sorry，I think “macc” means  multiply and accumulate
But， what does ‘activation’ mean？
In your analysis， input data also need “activation” computation， what does that mean？
Thanks！

**Comment by dgschwend** [comment]
Regarding MACC, see [https://github.com/dgschwend/netscope/issues/10](https://github.com/dgschwend/netscope/issues/10).
Activation does not refer to a computation, but to memory: Activation memory = memory needed to store the activations/blobs/layer results, Param memory = memory needed to store the parameters/weights.

**Comment by LiYijin** [comment]
Thanks！ I got it！ Really Thanks！
