### ISSUE TITLE
Error encountered: Unknown layer: reshape 

### ISSUE THREAD

**Issue by tankienleong** [dgschwend/netscope#9]
Hi, can you include the reshape layer into netscope? Thanks.

**Comment by dgschwend** [comment]
Hi! I think I already included reshape layers in my local branch. I'll see if I can push the relevant changes into the master repository.

**Comment by dgschwend** [comment]
Okay, just pushed commit https://github.com/dgschwend/netscope/commit/0810324cdbf56b61838ed855ba0a6f3563443e01, you should now be able to use reshape layers. Can you give it a try?

**Comment by tankienleong** [comment]
Thank you for included the reshape layer into netscope! 
But the network analysis shows the input dimension to reshape layer is 0x0 and there is no output dimension. 
Please refer to the attached screenshot.   
![untitled](https://cloud.githubusercontent.com/assets/25731934/25303675/8058014a-278a-11e7-8979-093ec501ad97.jpg)

**Comment by dgschwend** [comment]
Could you try again now?

**Comment by tankienleong** [comment]
The input dimension and channel are correct but the output dimension still remain 0xNaN.
![untitled](https://cloud.githubusercontent.com/assets/25731934/25304101/e8bb9fe6-2792-11e7-90af-5466dfc1a3e0.jpg)

**Comment by dgschwend** [comment]
Fixed. If you're still having problems, please attach your .prototxt so I can track down the bug.

**Comment by tankienleong** [comment]
I still having problems with the reshape layer. The output dimension still remain 0xNaN.
I had attached my probe_image_prototxt.txt file for your reference.
Beside that, can you include the ROI Pooling layer, Python layer and Normalize layer into netscope? Thanks.

[probe_image_prototxt.txt](https://github.com/dgschwend/netscope/files/948962/probe_image_prototxt.txt)

**Comment by dgschwend** [comment]
I'll check later. ROI Pooling should be ok, normalize as well. Python layers are customizable, and I cannot include an analysis for every possible Python layer. However, I assume you're concerned with (Faster) R-CNN detection networks, so your Python layer will probably just handle the Region Proposal step (module: rpn.proposal_layer). I should be able to include that specific one.
By the way, what tool did you use to generate your prototxt? Looks interesting...

**Comment by tankienleong** [comment]
Yes, it is related to the Faster R-CNN detection network. I get the prototxt file from [https://github.com/ShuangLI59/person_search](url) and modified it. 
Thanks in advance.

**Comment by dgschwend** [comment]
Hi  @tankienleong 
I just added support for reshape, roi_pooling, region_proposal and normalize layers. Your network should analyze just fine.
Best regards
David

**Comment by tankienleong** [comment]
Hi @dgschwend 
Thank you very much! 
I really appreciate it!
Best regards
kienleong
